### PR TITLE
Fixed bug where config option wasn't that useful in child dirs.

### LINKED ISSUE #56: gulp-load-plugins as a dependency of a dependency not loading plugins
EDIT: Remove all comments until this one: https://github.com/jackfranklin/gulp-load-plugins/issues/56#issuecomment-71681420

I *think* this is the same as #35.

I have the following project which I use to quickly load up gulp tasks in projects where I work without duplicating code: https://github.com/Lostmyname/lmn-gulp-tasks

Pretty much the same file structure described in [this comment](https://github.com/jackfranklin/gulp-load-plugins/issues/35#issuecomment-49170938), and it's looking in the top package.json, not the bottom one:

```
~/Sites/lmn/monkey master*  6m 44s  ⇡
❯ npm install lmn-gulp-tasks
npm WARN package.json lmn-monkey@3.0.1 No repository field.
npm WARN package.json browsernizr@1.0.2 No repository field.
lmn-gulp-tasks@1.0.0 node_modules/lmn-gulp-tasks
├── jshint-stylish@1.0.0 (log-symbols@1.0.1, text-table@0.2.0, string-length@1.0.0, chalk@0.5.1)
├── gulp-plumber@0.6.6 (through2@0.6.3)
├── gulp-jshint@1.9.0 (rcloader@0.1.2, minimatch@1.0.0, lodash@2.4.1, through2@0.6.3)
├── gulp-util@3.0.2 (array-differ@1.0.0, object-assign@2.0.0, beeper@1.0.0, array-uniq@1.0.2, lodash._reinterpolate@2.4.1, replace-ext@0.0.1, minimist@1.1.0, chalk@0.5.1, multipipe@0.1.2, vinyl@0.4.6, through2@0.6.3, lodash.template@2.4.1, dateformat@1.0.11)
├── gulp-minify-css@0.4.3 (memory-cache@0.0.5, bufferstreams@0.0.2, through2@0.6.3, vinyl-sourcemaps-apply@0.1.4, clean-css@3.0.7)
├── stylus@0.49.3 (css-parse@1.7.0, mkdirp@0.3.5, debug@2.1.1, glob@3.2.11, sax@0.5.8, source-map@0.1.43)
├── gulp-compass@2.0.3 (which@1.0.8, through2@0.6.3)
├── jshint@2.6.0 (strip-json-comments@1.0.2, underscore@1.6.0, console-browserify@1.1.0, exit@0.1.2, minimatch@1.0.0, shelljs@0.3.0, cli@0.6.5, htmlparser2@3.8.2)
├── gulp-jscs@1.4.0 (object-assign@2.0.0, through2@0.6.3, jscs@1.10.0)
├── gulp-autoprefixer@2.1.0 (object-assign@2.0.0, through2@0.6.3, vinyl-sourcemaps-apply@0.1.4, autoprefixer-core@5.0.0)
└── browserify@8.1.1 (https-browserify@0.0.0, tty-browserify@0.0.0, builtins@0.0.7, constants-browserify@0.0.1, process@0.10.0, path-browserify@0.0.0, os-browserify@0.1.2, isarray@0.0.1, inherits@2.0.1, commondir@0.0.1, string_decoder@0.10.31, stream-browserify@1.0.0, defined@0.0.0, domain-browser@1.1.3, shell-quote@0.0.1, xtend@3.0.0, shallow-copy@0.0.1, deep-equal@0.2.1, querystring-es3@0.2.1, assert@1.3.0, timers-browserify@1.2.0, punycode@1.2.4, util@0.10.3, vm-browserify@0.0.4, events@1.0.2, parents@1.0.1, console-browserify@1.1.0, subarg@1.0.0, url@0.10.2, readable-stream@1.0.33, http-browserify@1.7.0, deps-sort@1.3.5, through2@1.1.1, resolve@0.7.4, shasum@1.0.1, buffer@3.0.1, concat-stream@1.4.7, glob@4.3.5, duplexer2@0.0.2, browser-resolve@1.6.0, JSONStream@0.8.4, labeled-stream-splicer@1.0.2, browser-pack@3.2.0, crypto-browserify@3.9.10, umd@2.1.0, insert-module-globals@6.2.0, syntax-error@1.1.2, browserify-zlib@0.1.4, module-deps@3.6.4)

~/Sites/lmn/monkey master*  15s  ⇡
❯ gulp
[16:00:49] Using gulpfile ~/Sites/lmn/monkey/gulpfile.js
[16:00:49] Starting 'html'...
[16:00:49] Starting 'js-quality'...
[16:00:49] 'js-quality' errored after 8.71 ms
[16:00:49] Error: Cannot find module 'gulp-plumber'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.defineProperty.get (/Users/callumacrae/Sites/lmn/monkey/node_modules/gulp-load-plugins/index.js:56:18)
    at Gulp.jsQualityTask (/Users/callumacrae/Sites/lmn/monkey/node_modules/lmn-gulp-tasks/tasks/js-quality.js:15:33)
    at module.exports (/Users/callumacrae/Sites/lmn/monkey/node_modules/gulp/node_modules/orchestrator/lib/runTask.js:34:7)
    at Gulp.Orchestrator._runTask (/Users/callumacrae/Sites/lmn/monkey/node_modules/gulp/node_modules/orchestrator/index.js:273:3)
    at Gulp.Orchestrator._runStep (/Users/callumacrae/Sites/lmn/monkey/node_modules/gulp/node_modules/orchestrator/index.js:214:10)
    at Gulp.Orchestrator.start (/Users/callumacrae/Sites/lmn/monkey/node_modules/gulp/node_modules/orchestrator/index.js:134:8)
[16:00:49] Finished 'html' after 62 ms
```

If I replace `plugins.plumber(` with just `plumber(` and require it manually, it errors about the next module instead.

Interestingly, it doesn't happen if I npm link the `lmn-gulp-tasks` project in—it only happens when I actually install it through npm.

Any ideas what's happening?

### PR DESCRIPTION
**Pull request by callumacrae**
Fixes #56. I feel this probably needs a test, but I'm not sure how to
test it without adding a test dir and extra files. It works in my case,
and none of the existing tests break.

To test, just make a child directory with a gulpfile in and a couple
gulp-* dependencies, and require gulp-load-plugins using '../'. Then
it won't be able to find the dependencies until you merge this PR.

I can get rid of the editorconfig stuff if you want :)

### CODE REVIEW

**Comment by jackfranklin** [comment]
Thanks! I need to take some time to properly look at this, but will try to get back to you soon

**Comment by jackfranklin** [comment]
> without adding a test dir and extra files.

This feels complex enough that if that stuff needs to be added, happy to do it.

**Comment by callumacrae** [comment]
I added a test. Running the test on master fails, running it on this branch succeeds. Cleaning it up and committing now :smile: 

```
~/Sites/gulp-load-plugins config-fix*
❯ npm test

> gulp-load-plugins@0.8.0 test /Users/callumacrae/Sites/gulp-load-plugins
> mocha



  configuration
    ✓ throws a nice error if no configuration is found

  no lazy loading
    ✓ loads things in
    ✓ can take a pattern override
    ✓ allows camelizing to be turned off
    ✓ camelizes plugins name by default
    ✓ lets something be completely renamed
    ✓ does require at first

  with lazy loading
    ✓ loads things in
    ✓ can take a pattern override
    ✓ allows camelizing to be turned off
    ✓ camelizes plugins name by default
    ✓ lets something be completely renamed
    ✓ does not require at first
    ✓ does when the property is accessed

  requiring from another directory
    ✓ allows you to use in a lower directory


  15 passing (10ms)


~/Sites/gulp-load-plugins config-fix*
❯ git checkout -
M	package.json
D	test.js
A	test/index.js
Switched to branch 'master'
Your branch is up-to-date with 'origin/master'.

~/Sites/gulp-load-plugins master*
❯ npm test

> gulp-load-plugins@0.8.0 test /Users/callumacrae/Sites/gulp-load-plugins
> mocha



  configuration
    ✓ throws a nice error if no configuration is found

  no lazy loading
    ✓ loads things in
    ✓ can take a pattern override
    ✓ allows camelizing to be turned off
    ✓ camelizes plugins name by default
    ✓ lets something be completely renamed
    ✓ does require at first

  with lazy loading
    ✓ loads things in
    ✓ can take a pattern override
    ✓ allows camelizing to be turned off
    ✓ camelizes plugins name by default
    ✓ lets something be completely renamed
    ✓ does not require at first
    ✓ does when the property is accessed

  requiring from another directory
    1) allows you to use in a lower directory


  14 passing (28ms)
  1 failing

  1) requiring from another directory allows you to use in a lower directory:
     Error: Cannot find module 'gulp-test'
      at Function.Module._resolveFilename (module.js:338:15)
      at Function.Module._load (module.js:280:25)
      at Module.require (module.js:364:17)
      at require (module.js:380:17)
      at Object.defineProperty.get (/Users/callumacrae/Sites/gulp-load-plugins/index.js:56:18)
      at Context.<anonymous> (/Users/callumacrae/Sites/gulp-load-plugins/test/index.js:194:29)
      at callFn (/Users/callumacrae/Sites/gulp-load-plugins/node_modules/mocha/lib/runnable.js:251:21)
      at Test.Runnable.run (/Users/callumacrae/Sites/gulp-load-plugins/node_modules/mocha/lib/runnable.js:244:7)
      at Runner.runTest (/Users/callumacrae/Sites/gulp-load-plugins/node_modules/mocha/lib/runner.js:374:10)
      at /Users/callumacrae/Sites/gulp-load-plugins/node_modules/mocha/lib/runner.js:452:12
      at next (/Users/callumacrae/Sites/gulp-load-plugins/node_modules/mocha/lib/runner.js:299:14)
      at /Users/callumacrae/Sites/gulp-load-plugins/node_modules/mocha/lib/runner.js:309:7
      at next (/Users/callumacrae/Sites/gulp-load-plugins/node_modules/mocha/lib/runner.js:248:23)
      at Object._onImmediate (/Users/callumacrae/Sites/gulp-load-plugins/node_modules/mocha/lib/runner.js:276:5)
      at processImmediate [as _immediateCallback] (timers.js:354:15)



npm ERR! Test failed.  See above for more details.
npm ERR! not ok code 0
```

**Comment by callumacrae** [comment]
Done. Commit cherry-picks fine onto master to test that it fails there (or I can send another pull request if you want Travis to run the tests).

**Comment by callumacrae** [comment]
Marked WIP: I hadn't thought about what would happen if the module to be required was further up the tree, too! This PR as is could break that as it's specifying a relative path.

**Comment by callumacrae** [comment]
The latest commit will fix an issue I mentioned in #56 where `foo/bar/package.json` wouldn't be able to require `foo/node_modules/gulp-test`. Works fine now.

**Comment by callumacrae** [comment]
@jackfranklin Hey, any update on this?

**Comment by jackfranklin** [comment]
Hey, I'm away on hols with limited internet at the moment. Sorry for such a low response on my end, I'll get back to you early next week.

**Comment by callumacrae** [comment]
No worries! Enjoy your holidays.

File: .gitignore [hunk 1]
```diff
@@ -1 +1 @@
-node_modules
+/node_modules
```
Comment (jackfranklin) [inline .gitignore]: do you actually need the slash?

File: .editorconfig [hunk 2]
```diff
@@ -0,0 +1,7 @@
+root = true
+
+[*]
+end_of_line = lf
+insert_final_newline = true
+indent_style = space
+indent_size = 2
```
Comment (jackfranklin) [inline .editorconfig]: hey, this is good, but can we shift it into a separate PR? :)

File: index.js [hunk 3]
```diff
@@ -15,6 +15,7 @@ function camelize(str) {
 
 module.exports = function(options) {
   var finalObject = {};
+  var configObject, requireFn;
```
Comment (jackfranklin) [inline index.js]:
```
var configObject;
var requireFn;
```

File: index.js [hunk 4]
```diff
@@ -23,19 +24,27 @@ module.exports = function(options) {
...
 
-  if (typeof config === 'string') {
-    config = require(config);
+  if(typeof options.requireFn === 'function') {
+    requireFn = options.requireFn;
+  } else if(typeof config === 'string') {
+    requireFn = function (name) {
+      var searchFor = path.join('node_modules', name);
+      return require(findup(searchFor, {cwd: path.dirname(config)}));
+    };
```
Comment (jackfranklin) [inline index.js]: could we add a comment around this block explaining what it's there for? Maybe with a link to this PR or the issue.

File: package.json [hunk 5]
```diff
@@ -28,6 +28,7 @@
   "license": "MIT",
   "dependencies": {
     "findup-sync": "^0.2.1",
+    "gulp-uglify": "^1.1.0",
```
Comment (jackfranklin) [inline package.json]: why is this here?

**Comment by jackfranklin** [comment]
@callumacrae nice stuff, thanks for the contrib! Few comments but nothing major.

Also make sure to add yourself to the package.json as a contributor.

File: .gitignore (hunk 1 above)
Comment (callumacrae) [inline .gitignore]: Yep, otherwise the node_modules in the test dir is ignored.

File: .editorconfig (hunk 2 above)
Comment (callumacrae) [inline .editorconfig]: Done—I've left the commit in this PR, if you merge that one it'll disappear from this one (or I can rebase it out).

File: package.json (hunk 5 above)
Comment (callumacrae) [inline package.json]: I have no idea how that got there, I'll remove it now.

**Comment by callumacrae** [comment]
I've made all the changed you requested :smiley:

File: .gitignore (hunk 1 above)
Comment (jackfranklin) [inline .gitignore]: +1

**Comment by jackfranklin** [comment]
You're awesome, thanks man. I see you're London based so let's go for a pint sometime!

**Comment by callumacrae** [comment]
I'm at FEL, I'm the short guy :D

**Comment by jackfranklin** [comment]
Well this just got weird... :P

**Comment by callumacrae** [comment]
Yeah, at FEL last month when they said you were speaking I was like "Woah, I just sent that guy a pull request!". Weird coincidence, I guess :)
